trigger: none
pool: apna-agent-pool

steps:

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '"$(System.DefaultWorkingDirectory)/Nested map/Parent Module"'
    backendServiceArm: 'next-level-service-connection'
    backendAzureRmStorageAccountName: 'itsolution'
    backendAzureRmContainerName: 'nextlevelcontainer'
    backendAzureRmKey: 'it.tfstate'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '"$(System.DefaultWorkingDirectory)/Nested map/Parent Module"'
    environmentServiceNameAzureRM: 'next-level-service-connection'






